export const POPULATE_BOARD = 'POPULATE_BOARD';
export const BOX_DELETE = 'BOX_DELETE';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const MOVE_BLOCKS_DOWN = 'MOVE_BLOCKS_DOWN';
export const GENERATE_NEW_BLOCKS = 'GENERATE_NEW_BLOCKS';
export const CHECK_IF_CAN_MOVE = 'CHECK_IF_CAN_MOVE';
